### ISSUE TITLE
expose SASL property to the logging subsystems

### ISSUE THREAD

**Issue by bcollard** [spring-projects/spring-amqp#1049]
**Affects Version(s):** 2.1.6.RELEASE

---

## Enhancement

It would be interesting to enforce the "EXTERNAL" SASL mechanism when a client is using a keystore with a client cert to authenticate against a RabbitMQ server.

See this S.O. discussion for more details: https://stackoverflow.com/questions/42851250/saslconfig-using-spring-rabbitmq-not-working

This behavior should exist by default on the logging subsystems (log4j & logback) or be customizable over a new attribute (~"SaslConfig"). See this class for log4j2: https://github.com/spring-projects/spring-amqp/blob/master/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/log4j2/AmqpAppender.java

**Comment by bcollard** [comment]
see also https://github.com/spring-projects/spring-boot/issues/6719

**Comment by garyrussell** [comment]
There are many properties on the underlying RabbitMQ connection factory and the factory there is not created by the Spring factory bean (it's created by the appender itself, which is outside of the Spring context).

Since there are so many properties, I propose adding

```java
protected void configureRabbitConnectionFactory(ConnectionFactory cf) {
}
```

so users can subclass the Appenders and perform additional configuration as necessary.

I believe that would suit your needs?

**Comment by artembilan** [comment]
I see there is on the `RabbitConnectionFactoryBean`:
```
/**
	 * @param saslConfig the sasl config.
	 * @see com.rabbitmq.client.ConnectionFactory#setSaslConfig(com.rabbitmq.client.SaslConfig)
	 */
	public void setSaslConfig(SaslConfig saslConfig) {
		this.connectionFactory.setSaslConfig(saslConfig);
	}
```

and this one available for access from the overridden `configureRabbitConnectionFactory(RabbitConnectionFactoryBean)`.

So, I think we are covered already and no need in a new method. Only the problem that Log4J appenders are based on `@PluginFactory` static method to be created. So, provide some customization into an `AmqpAppender` we need to pay some effort into an extension. essentially fully custom `AmqpAppender` .

Any other thoughts how to overcome `static` restrictions?

**Comment by garyrussell** [comment]
I didn't notice that we already have that method.

Looks like having protected methods there is useless though due to the static creation.

Given that we already support other SSL props, we should just go ahead and add this one.

Given the static class, and it already has SSL support, we should just go ahead.

**Comment by bcollard** [comment]
Yes, indeed, extending the AMQPAppender is one solution.

I would simply go for this kind of change: https://github.com/bcollard/spring-amqp/commit/141dcda6b74a678e2b80dc0caa0e24b9d822debc

But I don't know about side effects here.

**Comment by bcollard** [comment]
So quick, so cool! thanks.
