### ISSUE TITLE
spring amqp 2.1.9 has an invalid POM

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-amqp#1082]
I am trying to consume the Spring AMQP `2.1.9.RELEASE` to release the next maintenance release of Spring Boot.

It looks like the published pom is invalid:

```
[WARNING] The POM for org.springframework.amqp:spring-amqp:jar:2.1.9.RELEASE is invalid, transitive dependencies (if any) will not be available: 3 problems were encountered while building the effective model for org.springframework.amqp:spring-amqp:2.1.9.RELEASE
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-core:jar is missing. @
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.core:jackson-databind:jar is missing. @
[ERROR] 'dependencies.dependency.version' for com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar is missing. @
```

I can see that [the released pom](https://search.maven.org/artifact/org.springframework.amqp/spring-amqp/2.1.9.RELEASE/jar) has indeed a reference to 3 jackson artifacts without a version.

**Comment by garyrussell** [comment]
Stephane, we recently switched to using Jackson's BOM; we saw this issue but I thought we had resolved it.

https://github.com/spring-projects/spring-amqp/blob/e3d825d4709ef9813b3165a2a5e92a9acc04c2a6/publish-maven.gradle#L23-L26

I am on PTO this week (and most of next).

I would go ahead and release Boot 2.1.8 with the previous spring-amqp rather than holding up the release. There are only a couple of bug fixes in 2.1.9.

**Comment by garyrussell** [comment]
Oh - that was on master; I see @artembilan backported it without the pom generation change.

https://github.com/spring-projects/spring-amqp/commit/1cbe7fb1e0d9b309faab3b7e6245004a0774ba72

cc/ @bclozel

**Comment by snicoll** [comment]
@garyrussell did you mean to close this one? Or supersede by the PR Brian created maybe?

**Comment by garyrussell** [comment]
We will keep this open and close it when Brian's PR is merged. (We have a different workflow to Boot's).

**Comment by snicoll** [comment]
> We will keep this open and close it when Brian's PR is merged

The issue is closed now, that's why I am asking.

**Comment by garyrussell** [comment]
Doh. Sorry. Artifact of using GitHub on my phone.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-projects/spring-amqp/commit/97585524ca47b1b79e43ef6eebbf2f49210ef4a5

Well, looks like Gradle can resolve those missed versions somehow, because I tested this release in Spring Integration.
But might be not Maven.
So, I need to keep in mind to test samples as well. 
Or just don't do such a change before releasing... 😄 

Thank you all for help on this!
