### ISSUE TITLE
The reply-to container is initialized lazily and shouldn't be binding its routing connection factory key to the calling thread

### ISSUE THREAD

**Issue by jandres80** [spring-projects/spring-amqp#1091]
**Affects Version(s):** \<2.1.6>

Getting "IllegalArgumentException" errors trying to do the following:

Receive an AMQP message that forces me to stop a "SimpleMessageListenerContainer".
Make an AMQP request using the "direct reply-to" mechanism.
Restart the "SimpleMessageListenerContainer"

More details in:

https://stackoverflow.com/questions/57906682/simplemessagelistenercontainer-and-illegalargumentexception

---

**Comment by garyrussell** [comment]
Can you explain your use of the `RoutingConnectionFactory`? Please show its configuration.

It turns out that this code is required in order to use the correct `targetConnectionFactory` when running a connection listener (if present). [Orignal SO issue here](https://stackoverflow.com/questions/42784471/spring-amqp-mix-simpleroutingconnectionfactory-with-rabbitlistener).

The problem is that the `RoutingConnectionFactory`'s `routingLookupKey` is bound to the thread with the SMLC's queue name and we can't rebind it with another key (for the DRTMLC). In any case, I suspect you won't get a hit on the lookup anyway (unless you have configured that key as well in the RCF).

Is there any way you can avoid using the `simpleRoutingConnectionFactory()` in the template for the send and receive?

**Comment by garyrussell** [comment]
I found a solution.
