### ISSUE TITLE
usePublisherConnection in RabbitTemplate should default to true

### ISSUE THREAD

**Issue by kjastrzebski** [spring-projects/spring-amqp#1099]
According to docs in setUsePublisherConnection() setter in RabbitTemplate, usePublisherConnection field should default to true since version 2.1. For me it looks like this still defaults to false.

**Comment by garyrussell** [comment]
We need to change the javadoc instead. It turned out that `true` is not a safe default and will break many existing applications. 

The problem is that any auto-delete, exclusive `Queue` beans in the application context will be declared on the producer connection and any listener containers that consume from those queues will fail to start because they can only be accessed on the connection on which they were declared.
