### ISSUE TITLE
RoutingConectionFactory doesn't work with @RequestScope and RabbitListenerConfigurer

### ISSUE THREAD

**Issue by thundur** [spring-projects/spring-amqp#1121]
I'm using a routing connection factory for multi-tenancy. And I'm registering RabbitListenerEndpoints by hand to listen to different instances of RabbitMQ per tenant. This is working nicely, but when I annotate my RoutingConnectionFactory bean with @RefreshScope, the application doesn't look up the proper target connection factory from the RoutingConnectionFactory.

This is caused by AbstractMessageListenerContainer.getConnectionFactory(), which checks whether the connection factory is a RoutingConnectionFactory and looks up the target connection factory if it is. This is done by using instanceof, but in the case of @RequestScope, the bean is proxied (with JDK dynamic proxy), so the instanceof check doesn't work. Setting the proxy mode to TARGET_CLASS will still produce a JDK dynamic proxy.

The solution would be to (also) check whether the target object from the proxied object is a RoutingConnectionFactory.

Reproduction:
- Open the attached Spring boot project
- Set a breakpoint in AbstractMessageListenerContainer.getConnectionFactory()
- Debug the project and check that the instanceof check yields false.
- Remove the @RefreshScope annotations in RoutingTestApplication.java
- Debug again and see that the instanceof check yields true now.

I encountered this problem in both spring-rabbit 2.1.11 and 2.1.12.

[routing-test.zip](https://github.com/spring-projects/spring-amqp/files/3840438/routing-test.zip)

**Comment by garyrussell** [comment]
`RoutingConnectionFactory` is an interface so it should be implemented by the proxy. I'll take a look at your test case.

Bear in mind that putting a "live" bean like a connection factory will likely cause some nasty side effects when a refresh occurs, including, but not limited to:

* Duplicate deliveries due to a failure to acknowledge a message that was being processed when the refresh occurred.
* Failure to publish if the refresh occurs between the template getting a channel and publishing.

**Comment by garyrussell** [comment]
It's because you defined the bean as 

```
  @Bean
  @RefreshScope
  public ConnectionFactory routingConnectionFactory() {
```

The refresh scope proxies just that interface.

You can't use this either...

```
  @Bean
  @RefreshScope
  public RoutingConnectionFactory routingConnectionFactory() {
```

for the same reason - you can't cast it here

```
    simpleRabbitListenerContainerFactory.setConnectionFactory((ConnectionFactory) routingConnectionFactory());
```

for the same reason - only RCF is proxied.

This works, with a CGLIB proxy being the result...

```
  @Bean
  @RefreshScope
  public SimpleRoutingConnectionFactory routingConnectionFactory() {
```

So, it seems to me it's a bug in `RefreshScope` - they should add all the implemented interfaces on the proxied class.

**Comment by thundur** [comment]
Thanks for your response, I worked around it for now by using the concrete implementation type instead of the interface, per your last example!
I'll file an issue with spring-cloud to ask about the proxying.

**Comment by garyrussell** [comment]
See https://github.com/spring-cloud/spring-cloud-commons/issues/636
