### ISSUE TITLE
Why prompt 'Attribute value must be constant'

### ISSUE THREAD

**Issue by hanyu658** [spring-projects/spring-amqp#1361]
I want to add prefix to the queue name , but I puzzled why I can't use string.concat () to concatenate.
If I don't use '${}', maybe you can give me a more elegant solution.

```java
package com.example.demo.config;

import org.springframework.amqp.rabbit.annotation.RabbitListener;

public class Test {

    public static class Queue {
        private static final String PREFIX = "prefix-";
        public static final String QUEUE_NAME_1 = PREFIX + "my-queue";
        public static final String QUEUE_NAME_2 = PREFIX.concat("my-queue");
    }

    @RabbitListener(queues = Queue.QUEUE_NAME_1)
    void a() {
    }

    @RabbitListener(queues = Queue.QUEUE_NAME_2)
    void b() {
    }
}
```

**Comment by garyrussell** [comment]
GitHub issues are NOT for asking questions. Did you not read the instructions?

>## Question

>Please ask questions about how to use something, or to understand why something isn't
working as you expect it to, on
[Stack Overflow using the `spring-amqp` tag](https://stackoverflow.com/questions/tagged/spring-amqp).

You can also use GitHub discussions for questions https://github.com/spring-projects/spring-amqp/discussions

It is simply a rule of Java, annotation property values must be constants (not computed).

The compiler will allow
```java
@RabbitListener(queues = PREFIX + "my-queue")
```
because the concatenation is done by the compiler.
