### ISSUE TITLE
Unable to connect to RabbitMQ Stream

### ISSUE THREAD

**Issue by Lixuhuilll** [spring-projects/spring-amqp#2522]
**In what version(s) of Spring AMQP are you seeing this issue?**

3.1.3

**Describe the bug**

When I use version 3.1.3 of SpringBoot and import spring-boot-starter-amqp and spring-rabbit-stream, once I listen to any Stream, it will fail to start.

**Expected behavior**

Start and listen to Stream normally.

**Sample**

https://github.com/Lixuhuilll/demo-rabbit-stream.git

**Comment by Lixuhuilll** [comment]
Fill in my RabbitMQ info：
![屏幕截图 2023-09-12 160049](https://github.com/spring-projects/spring-amqp/assets/88485037/e287d1a0-5f43-4202-9cd5-7e954e5c165b)
![屏幕截图 2023-09-12 160039](https://github.com/spring-projects/spring-amqp/assets/88485037/e3309e70-ad3d-4e39-9aff-3c251cc0d822)

**Comment by artembilan** [comment]
I have figured out that it works like this:
```
    @Bean
    EnvironmentBuilderCustomizer environmentBuilderCustomizer(RabbitProperties rabbitProperties) {
        RabbitProperties.Stream rabbitStreamProperties = rabbitProperties.getStream();
        return builder -> builder
                .addressResolver(add -> new Address(rabbitStreamProperties.getHost(), rabbitStreamProperties.getPort()));
    }
```
The plain `host/port` provided by Spring Boot in the `RabbitStreamConfiguration` doesn't work somehow.
Plus you have a problem in the `@RabbitListener` method.
since you are asking for the `spring.rabbitmq.listener.stream.native-listener=true`, you have to expect a stream message instead:
```
    @RabbitListener(id = "consumer", queues = "stream.test")
    public void consumerStream0(com.rabbitmq.stream.Message msg) {
```
Now after running your application and publishing message to that stream I got this in logs:
```
2023-09-12T12:04:57.284-04:00  INFO 17068 --- [pool-5-thread-1] c.e.d.DemoRabbitStreamApplication        : consumer-0-0:Data{Hello from issue #2522}
```

I'll discuss with RabbitMQ team what is wrong with plain `host/port` provided at the moment by Spring Boot.

**Comment by michaelklishin** [comment]
We are looking into what may be going on with @artembilan but it's worth mentioning that the RabbitMQ Stream protocol is different from the messaging protocols RabbitMQ supports in several important ways, in particular that clients perform cluster topology discovery.

Please [see this post](https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/), in particular if you use a load balancer in your environment.

**Comment by Lixuhuilll** [comment]
Thanks for your help. After using Artem Bilan's method, RabbitMQ Stream can now be successfully connected.
I have only tested it locally on a single machine, not in a cluster.

**Comment by artembilan** [comment]
Thanks for confirmation.
I'm transferring this issue to Spring Boot since there is nothing wrong on Spring AMQP side and we need to revise how we auto-configure an `Environment` for RabbitMQ Stream for those `host/port`.
Or add more properties to map properly to Stream topology or so.

**Comment by wilkinsona** [comment]
Having read the "Connecting to Streams" blog post, given that there's neither a load balancer nor a cluster involved here I don't understand why Boot's configuration of just the `host` and `port` does not work. Shouldn't Rabbit's default behavior of using the address as-is work in this case, @michaelklishin?

The blog post describes configuring an address resolver the returns a hard-coded host and port as a workaround for when a load balancer is in use. As such, it doesn't sound like a generally applicable change that should be made in Boot.

**Comment by michaelklishin** [comment]
@wilkinsona my best guess would be that the node reports hostname A but the client resolves hostname B, and they are not identical. On Slack, @acogoluegnes has recommended using

``` java
.addressResolver(add -> new Address(rabbitStreamProperties.getHost(), rabbitStreamProperties.getPort()));
```

which effectively ignores the server-advertised values.

Without debug logs we can only guess. And I'm not sure if we log the advertised hostname in the stream client. If not, we should.

**Comment by wilkinsona** [comment]
Thanks. That's similar to the recommendation in the blog post and I am still not sure that it's generally applicable such that the change should be made in Boot. It would mean that the server-advertised values are ignored by default. If that's appropriate default behavior, I would expect the stream client's default resolver to behave in this way, using the host and port configured on the `com.rabbitmq.stream.Environment` rather than returning the address as-is.

**Comment by Lixuhuilll** [comment]
I actually uploaded a log of connection failures in the sample if you need logs.

https://github.com/Lixuhuilll/demo-rabbit-stream/commit/02e5ac998e73462ccf73d9bfb1d5a49fa312d6f5/logs/log.log

**Comment by michaelklishin** [comment]
For environments where there's just one node or an LB is used, ignoring server-advertised values is fine. But if you want direct parallel connections because, well, that's the option that offers the best throughput, you have to make sure that the server advertises hosts that the clients will be able to connect to.

Which is why I've asked @artembilan for an easy way to configure Spring projects for both scenarios, with the LB one perhaps being a more reasonable default.

**Comment by acogoluegnes** [comment]
How is the broker started (Docker container or not)? Is it running locally?

Can you enable `debug` log level for `com.rabbitmq.stream.impl` and share the output?

**Comment by Lixuhuilll** [comment]
> How is the broker started (Docker container or not)? Is it running locally?
> 
> Can you enable `debug` log level for `com.rabbitmq.stream.impl` and share the output?

I didn't use container,broker runs directly on the local machine. And I didn't modify any of the default configurations, only installed the required plugins.

This is a log with `logging.level.com.rabbitmq.stream.impl=debug`:
[debug-log.log](https://github.com/spring-projects/spring-amqp/files/12599532/debug-log.log)

**Comment by acogoluegnes** [comment]
The client uses localhost to connect first, as instructed by Spring Boot. Then it uses the host returned by the stream discovery mechanism (`Xuhui_LapTop`). The host is visible, but you're using the `guest` user, which can connect only from localhost, that's why you're getting the `AUTHENTICATION_FAILURE_LOOPBACK` error.

You can force the use of localhost with the [load balancer trick](https://blog.rabbitmq.com/posts/2021/07/connecting-to-streams/#using-the-stream-java-client-with-a-load-balancer) or by telling the [broker to always return localhost for discovery](https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-first-application/#starting-rabbitmq-with-streams-enabled) with the `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` environment variable.

You also use another user than `guest`.

**Comment by michaelklishin** [comment]
And out of those three, the easiest option for Spring to adopt is the load balancer-friendly setting.

@acogoluegnes maybe nodes could return `localhost` at discovery stage if we know the client has connected from localhost? It should be both safe and the most logical thing to do, avoiding explicit configuration. Am I missing something that would make it an unrealistic thing to do?

**Comment by wilkinsona** [comment]
> And out of those three, the easiest option for Spring to adopt is the load balancer-friendly setting.

It's easy to adopt, but I don't think you've addressed why it isn't the default behavior of the Rabbit Stream client. Why should Spring Boot's default behaviour be different?

**Comment by michaelklishin** [comment]
@wilkinsona the default is connect using the discovery mechanism in the client. It works fairly well in practices outside of Kubernetes, where LBs are present 99% of the time.

We had no reason to switch to the "LB-friendly" option by default. Maybe we should. It's a pity that a protocol built for parallelism has to be dumbed down and hidden behind such defaults and load balancers but oh well.

**Comment by Lixuhuilll** [comment]
Maybe just a more user-friendly log prompt or documentation so I don't have a hard time finding the problem.

**Comment by michaelklishin** [comment]
@Lixuhuilll users generally do not read documentation until they hit an issue, this is one thing that I am very confident in saying given my ≈ 13 years of experience as a RabbitMQ contributor.

https://github.com/rabbitmq/rabbitmq-server/issues/9424 should help with local clients running in the host. With Docker, this gets very multi-dimensional. Docker users will have to explicitly configure some things, just like they have to explicitly set up port forwarding or use non-standard ports.

**Comment by wilkinsona** [comment]
Testcontainers advises against using `localhost` to address a service running in a container and suggests using `getHost()` instead. It would be interesting to know if that improves the situation here.

**Comment by michaelklishin** [comment]
As long as RabbitMQ nodes resolve what `getHost()` returns, it should make this specific issue go away. But the issue with ports when containers are used would have to be addressed differently, for instance, using port forwarding to the host.

**Comment by garyrussell** [comment]
>Testcontainers advises against ...

@artembilan @wilkinsona Within the framework itself, for test containers we use 

```java
RABBITMQ = new RabbitMQContainer(imageName)
		.withExposedPorts(5672, 15672, 5552)
		.withPluginsEnabled("rabbitmq_stream")
		.withStartupTimeout(Duration.ofMinutes(2));
```
```java
	public static int streamPort() {
		return RABBITMQ != null ? RABBITMQ.getMappedPort(5552) : 5552;
	}
```
and
```java
		@Bean
		static Environment environment() {
			return Environment.builder()
					.addressResolver(add -> new Address("localhost", streamPort()))
					.build();
		}
```

i.e. we don't tell TC to use localhost, we simply use a custom address resolver.

Not particularly relevant to this issue; I just wanted to clarify that we don't go against TC's advice within the framework itself.

**Comment by artembilan** [comment]
As far s I know the `getHost()` retunrs something randomly assigned to the container by Docker.
At the same time the exposed is also randomly assigned by Docker.
Even if RabbitMQ in that Docker container knows about its host name to advertise properly, the mapped port is not known, therefore a locator for Stream (or whatever we ask for connection props) does not return a proper info for us.
More over as we discussed before, with default `guest` credentials we cannot connect to something what is not `localhost`.

**Comment by garyrussell** [comment]
Right; so when using Docker locally, use a custom address resolver.

**Comment by artembilan** [comment]
With this `.host(RabbitTestContainer.RABBITMQ.getHost()).port(RabbitTestContainer.streamPort())`, if I don't use `.withEnv("RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS", "-rabbitmq_stream advertised_host localhost")`, it fails like:
```
Caused by: java.net.UnknownHostException: No such host is known (9c17fdf2283a)
```
If I do advertise host on the container:
```
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:5552
```

I probably hijacked this issue, but who knows if end-user is going to try defaults against local RabbitMQ broker or the one by Testcontainers...

**Comment by michaelklishin** [comment]
FYI, https://github.com/rabbitmq/rabbitmq-stream-java-client/pull/420 will ship in RabbitMQ Stream client 0.13.0 (I don't have an ETA).

**Comment by artembilan** [comment]
I want to say thank you to everyone involved in the fix.
I've just pushed the fix for the tests after upgrading to the latest `com.rabbitmq:stream-client`.
So, now no need in a custom `AddressResolver` and simply setting the port (if random) against local developer environment is fully enough.
And that is exactly what is expected by Spring Boot auto-configuration.

**Comment by acogoluegnes** [comment]
Thanks for the follow-up @artembilan. The [last paragraph of this section of the documentation](https://rabbitmq.github.io/rabbitmq-stream-java-client/stable/htmlsingle/#understanding-connection-logic) describes the behavior:

> To make the local development experience simple, the client library can choose to always use `localhost` for producers and consumers. This happens if the following conditions are met: the initial host to connect to is `localhost`, the user is `guest`, and no custom address resolver has been provided. Provide a pass-through `AddressResolver` to `EnvironmentBuilder#addressResolver(AddressResolver)` to avoid this behavior. It is unlikely this behavior applies for any real-world deployment, where `localhost` and/or the default `guest` user should not be used.
