### ISSUE TITLE
Unable to access AMQP Channel from RabbitListenerErrorHandler in case of MessageConversionException

### ISSUE THREAD

**Issue by cryy** [spring-projects/spring-amqp#2652]
**In what version(s) of Spring AMQP are you seeing this issue?**

3.1.2

**Describe the bug**

Whenever a `MessageConversionException` occurs, the raw Spring message returned in `RabbitListenerErrorHandler#handleError` is null. Channel information is being stored inside of that raw message as per #1013.

This presents a problem for manual ack mode, as the channel information information is lost and you cannot manually ack the message, leaving it stuck in the queue. Is there any particular reason why the channel is not forwarded through the error handler arguments?

**To Reproduce**

Call any method that sends messages and converts objects via `RabbitTemplate` and attempt to convert an unsupported object.

**Expected behavior**

The error handler should return the Channel object whenever a message had been published.

**Sample**

N/A

**Comment by artembilan** [comment]
OK. I think I'll change the contract of the `RabbitListenerErrorHandler` to accept a `Channel` as separate argument.
It is always available even we we have just failed to convert a message.

It is going to be in several cycles since we cannot just make a breaking change.
So, first of all we deprecate an existing method and introduce a new one as `default`.
In the next `3.2` version we will address it respectively.

Thanks for the report!
