### ISSUE TITLE
Is AbstractConnectionFactory need to register itself as an AMQConnection's ShutdownListener when a new connection was created?

### ISSUE THREAD

**Issue by welsper-young** [spring-projects/spring-amqp#2891]
Thus we can receive an AMQConnection shutdown signal.
For CachingConnectionFactory, it does do this thing for AMQChannel creation at line 712:
https://github.com/spring-projects/spring-amqp/blob/ccca9d9b8e5d2d2c2e6afe0c71353292363b77f7/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/CachingConnectionFactory.java#L698-L714

We can do this within below codes maybe?
For example, add `rabbitConnection.addShutdownListener(this);` under line 584.
https://github.com/spring-projects/spring-amqp/blob/ccca9d9b8e5d2d2c2e6afe0c71353292363b77f7/spring-rabbit/src/main/java/org/springframework/amqp/rabbit/connection/AbstractConnectionFactory.java#L580-L626

Currently, I do this at ConnectionListener's onCreate method instead which is not straightforward.
```java
abstractConnectionFactory.addConnectionListener(new ConnectionListener() {
    @Override
    public void onCreate(Connection connection) {
        // Do something.
        connection.getDelegate().addShutdownListener(new ShutdownListener() {
            @Override
            public void shutdownCompleted(ShutdownSignalException cause) {
                // Do something when the AMQConnection shutdown.
            }
        });
    }

    @Override
    public void onClose(Connection connection) {
        // Do something.
    }

    @Override
    public void onShutDown(ShutdownSignalException signal) {
        // Do something.
    }

    @Override
    public void onFailed(Exception exception) {
        // Do something.
    }
 });
```

**Comment by artembilan** [comment]
The `channel.addShutdownListener(this);` and `rabbitConnection.addShutdownListener(this);` are two different entities.
We just cannot compare them or replace one with another if I understood your request correctly.

I'm also not sure in your ` connection.getDelegate()` since it feels like something else is missed in your logic.

I agree that there is no easy way to implement your requirement with out-of-the-box `AbstractConnectionFactory` implementations.

I'll go ahead and add the mentioned `rabbitConnection.addShutdownListener(this);` into the `AbstractConnectionFactory#L580`.
Looks like `AbstractConnectionFactory.shutdownCompleted()` is aware of connection shutdowns as well.
