### ISSUE TITLE
Unexpected exchange type: headers

### ISSUE THREAD

**Issue by SergiusSidorov** [spring-projects/spring-amqp#408]
Hi!

When I try to bind queue to headers exchange through annotation `@RabbitListener -> bindings -> @QueueBinding`, I receive exception: `Unexpected exchange type: headers`

I inspect class `RabbitListenerAnnotationBeanPostProcessor` and found next code:

```java
if (exchangeType.equals(ExchangeTypes.DIRECT)) {
    exchange = new DirectExchange(exchangeName,
            resolveExpressionAsBoolean(bindingExchange.durable()),
            resolveExpressionAsBoolean(bindingExchange.autoDelete()));
    actualBinding = new Binding(queueName, DestinationType.QUEUE, exchangeName, resolvedKey, null);
}
else if (exchangeType.equals(ExchangeTypes.FANOUT)) {
    exchange = new FanoutExchange(exchangeName,
            resolveExpressionAsBoolean(bindingExchange.durable()),
            resolveExpressionAsBoolean(bindingExchange.autoDelete()));
    actualBinding = new Binding(queueName, DestinationType.QUEUE, exchangeName, "", null);
}
else if (exchangeType.equals(ExchangeTypes.TOPIC)) {
    exchange = new TopicExchange(exchangeName,
            resolveExpressionAsBoolean(bindingExchange.durable()),
            resolveExpressionAsBoolean(bindingExchange.autoDelete()));
    actualBinding = new Binding(queueName, DestinationType.QUEUE, exchangeName, resolvedKey, null);
}
else {
    throw new BeanInitializationException("Unexpected exchange type: " + exchangeType);
}
```

i.e. binding to headers exchange not supported in annotation `@RabbitListener`.
Why?

**Comment by artembilan** [comment]
Well, pay attention, please, to the `@RabbitListener` with `bindings` configurations.
We found  it as already enough complicated.
And from other hand see the `HeadersExchange` [description](https://www.rabbitmq.com/tutorials/amqp-concepts.html) and its binding logic in the `HeadersExchangeMapConfigurer`. For example:
````java
BindingBuilder.bind(new Queue("q"))
				.to(new HeadersExchange("t"))
				.where("foo")
				.matches("bar");
````
But there are other configuration logical branches. 

So, we decided do not allow `HeadersExchange` from the annotation configuration and let end-users to do their sophisticated solutions with standard `BindingBuilder` and `@Bean` combinations:
````java
@Bean
public DirectExchange e1() {
	return new DirectExchange("e1", false, true);
}

@Bean
public Queue q1() {
	return new Queue("q1", false, false, true);
}

@Bean
public Binding b1() {
	return BindingBuilder.bind(q1()).to(e1()).with("k1");
}
````
Ultimately, the `@RabbitListener` is just for listener's method on the queue. And from big height it shouldn't know anything about bindings.

Hope that is clear

**Comment by garyrussell** [comment]
The [javadocs](http://docs.spring.io/spring-amqp/docs/current/api/index.html?org/springframework/amqp/rabbit/annotation/Exchange.html) document this limitation.

None of the exchanges declared by the `@QueueBinding` annotations support an `arguments` map - it's a bit awkward to build a map using annotations.

Since the headers exchange requires arguments for the header mapping and `x-match` argument, we couldn't support it without adding argument support, hence it's not currently supported.

The work around (and for any exchange requiring arguments) is to use external `@Bean` definitions.

We can revisit this if you feel strongly about it - if so, open a [JIRA Issue](https://jira.spring.io/browse/AMQP) and we'll take a look.

We'd need to add something like

    Argument[] arguments default {}

Where `Argument` would be an annotation, something like:

      {  @Argument(name="x-match", value="all",
         @Argument(name="foo", value="bar",
         @Argument(name="baz", value="qux" }

Now I see it laid out like that, it doesn't look like it would be too bad; however, if you configured queue arguments as well, the annotation could get very unwieldy, very quickly, and hard to read - hence my original thought that such configuration would be better done as `@Bean`s.

**Comment by SergiusSidorov** [comment]
The idea with the array of arguments looks great. In my opinion, this solution looks complete (all type of exchanges will be supported).
Write bindings on annotations isn't very nice solution. But this has a right to exist. Especially since it is already there for other types of exchanges.

**Comment by garyrussell** [comment]
https://jira.spring.io/browse/AMQP-604

**Comment by artembilan** [comment]
The PR #409 has been merged https://github.com/spring-projects/spring-amqp/commit/54a613a08e2154fffc8784c7964a85975f4d8fce
