### ISSUE TITLE
I have some suggestions

### ISSUE THREAD

**Issue by cky-thinker** [spring-projects/spring-amqp#714]
Recently, I needed to use spring-boot-amqp in my project, and I found some unreasonable places.
1.
@interface Exchange default value is durable=false, autoDelete=false
and the AbstractExchange default value is durable=true, autoDelete=false
if i run project by default ,it will throw exception
2.
I think it's more reasonable to explicitly specify the @interface Exchange#type instead of the default exchangetypes.direct, because you might forget to modify the type and make a mistake, it's not easy to find here, and it's normal to use the other type.

**Comment by artembilan** [comment]
You know, your question isn't clear.

Perhaps it would be better to start from StackOverflow and then we let you know there if it is still necessarily to raise an JIRA or GH issue?

Right now I just can't compile your request to some reasonable and valuable info as a bug or feature request.

Please, be more specific. Otherwise with such a subject we may consider your message as a spam and could just close it as invalid with any comments.

Also learn, please, how to comment on GitHub do not mention users for nothing: https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-people-and-teams

Thank you for understanding.

**Comment by garyrussell** [comment]
This is fixed in 2.0 [AMQP-733](https://jira.spring.io/browse/AMQP-733).

**Comment by garyrussell** [comment]
2 - Direct is a reasonable default; it would be a big breaking change to make this a required attribute, affecting many users.
