### ISSUE TITLE
Have an hierarchy for the MessageConverter based-ObjectMapper in Spring AMQP similar to Spring Web 

### ISSUE THREAD

**Issue by mhewedy** [spring-projects/spring-amqp#768]
Currently, the `Jackson2JsonMessageConverter` is tied with the JSON and we don't have a Jackson2 hierarchy abstraction as `AbstractJackson2HttpMessageConverter` of spring-mvc module.

We need to implement `Jackson2XmlMessageConverter` and create a new abstraction `AbstractJackson2HttpMessageConverter` to act as a parent for the new `Jackson2XmlMessageConverter` and the existing `Jackson2JsonMessageConverter`.

**Comment by artembilan** [comment]
Well, from big height your concern isn't clear and there are some typos in your post, but still I can guess that you would like to have a variant of the `Jackson2JsonMessageConverter` which can work exactly with XML. In other words you want to have an hierarchy for the `ObjectMapper` here in Spring AMQP similar what we have in Spring Web with the `AbstractJackson2HttpMessageConverter`.

As you said yourself the current `Jackson2JsonMessageConverter` is tied with the JSON, but that is exactly in its name. So, what we need is to extract some abstract `AbstractJackson2MessageConverter` and implement a `Jackson2XmlMessageConverter`.

If that is what you have in mind, then it is a good suggestion and contribution is always welcome.

Otherwise your issue is not clear. Sorry...

**Comment by mhewedy** [comment]
That is exactly what I meant, sorry for being my question not clear enough. 

I would prepare and send a PR. Thanks.

**Comment by mhewedy** [comment]
Noted; thanks.
