### ISSUE TITLE
about the SimpleMessageListenerContainer.addQueueNames(String... queueName)

### ISSUE THREAD

**Issue by Genitana** [spring-projects/spring-amqp#782]
I have a question about the   SimpleMessageListenerContainer.addQueueNames(String... queueName)  ,
 ```
   Add queue(s) to this container's list of queues. 
The existing consumers will be cancelled after they have processed any pre-fetched messages and new consumers will be created. 
The queue must exist to avoid problems when restarting the consumers.
```
why the  existing consumers have to cancelled  and created a new consumers  ?
Can the old consumer  add a new queue by  consumeFromQueue(String queue)    ?

**Comment by garyrussell** [comment]
Please don't use GitHub issues to ask questions; issues are for reporting bugs or asking for new features.

It was due to the way the code was architected. The newer `DirectMessageListenerContainer` does not need to do this; see [Choosing a Container](https://docs.spring.io/spring-amqp//reference/html/_reference.html#choose-container) for the differences between the two containers.
