### ISSUE TITLE
RabbitNamespaceHandler support config ListenerContainerFactoryBean#afterReceivePostProcessors

### ISSUE THREAD

**Issue by carl-zhao** [spring-projects/spring-amqp#794]
ListenerContainerFactoryBean has field afterReceivePostProcessors，but rabbit name space can not config this field.

**Comment by artembilan** [comment]
The XML support is slightly out of support, indeed.
It is in a low priority since people more and more these days configuring their Spring projects only with Java and annotations. Also with Kotlin.

We can fix this issue because you have requested it, however we also would like to see a contribution: https://github.com/spring-projects/spring-amqp/blob/master/CONTRIBUTING.adoc

So, if you are interested in this feature and would like to have a fix you are welcome to open Pull Request!

Just let us know how you prefer to proceed.

Thanks

**Comment by carl-zhao** [comment]
Well, I'd like to try it
