### ISSUE TITLE
received the value '5000' of type 'long' but current is none

### ISSUE THREAD

**Issue by aeasylife** [spring-projects/spring-amqp#806]
I try to add some parameters when creating Queue.
`
Map<String,Object> arguments = new HashMap<>();
arguments.put("x-expires", 5000L);
Queue queue = QueueBuilder.durable(“lc”).withArguments(arguments).build();
rabbitAdmin.declareQueue(queue);
`
There was a mistake in the statement.

`
com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'lc' in vhost 'dc': received the value '5000' of type 'long' but current is none, class-id=50, method-id=10)
`
I don't know how to specify parameter types.

**Comment by artembilan** [comment]
This happens because the queue `lc` already exists on the Broker and it is there without that `x-expires` attribute.
Or remove that queue on the broker, or don't declare it with this `x-expires` in the application. 
You can't modify queue after its creation.

Please, consider do not ask question here on GitHub in the future.
They have to be present on some Community forums, e.g. StackOverflow.

We use GitHub issues only for bug reports and new features requests.
