### ISSUE TITLE
RabbitMQ Heartbeat not active

### ISSUE THREAD

**Issue by alowrey** [spring-projects/spring-amqp#839]
RabbitMQ's `ConnectionFactory` exposes two properties related to the heartbeat: requestedHeartbeat and heartbeatExecutor. While requestedHeartbeat is configurable via the `spring.rabbitmq.requested-heartbeat` property, `heartbeatExecutor` is never configured, so I don't believe the client-side heartbeat is actually happening. The comment block in `ConnectionFactory` for `setHeartbeatExecutor` is here:

https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/ConnectionFactory.java#L620

Could this setter be exposed as a Spring property similar to how requestedHeartbeat is?

**Comment by artembilan** [comment]
The `setHeartbeatExecutor` is related to the `ScheduledExecutorService` object, meanwhile the `setRequestedHeartbeat()` is just for simple `int`.
So, Spring Boot configuration property for the `requestedHeartbeat` can be exposed and configured in the external environment or just simple properties or YAML file.
On the other hand the `ScheduledExecutorService` is not that kind of objects which can simply be presented as a literal in the external configuration.

That's why there is no any configuration property for this or similar setters.

At the same time when we take a look in the RabbitMQ Client code we will find this:

```
private ScheduledExecutorService createExecutorIfNecessary() {
        synchronized (this.monitor) {
            if (this.executor == null) {
                this.executor = Executors.newSingleThreadScheduledExecutor(threadFactory);
            }
            return this.executor;
        }
    }
```
in the `HeartbeatSender`.

So, there is a default one which is used internally. Therefore there is nothing to worry about and assume that "client-side heartbeat is **not** actually happening".

More over this doesn't look like a Spring AMQP project question.
All the configuration properties are managed by [Spring Boot](https://spring.io/projects/spring-boot).

Closing as `Invalid`.

Thanks for understanding!

**Comment by alowrey** [comment]
@artembilan My apologies, I missed the `HeartbeatSender` class. You're right that the frame is being sent based on that configuration. Thanks!
