### ISSUE TITLE
The recovery mechanism does not work when the queues are created using RabbitAdmin

### ISSUE THREAD

**Issue by andcuevas** [spring-projects/spring-amqp#900]
## Version Used

Spring Boot Starter 2.1.2
Spring Boot Starter AMQP 2.1.2

## Description of the problem
I created a demo project in order to reproduce the problem:
https://github.com/andcuevas/spring-rabbitmq-recovery-rabbit-admin-problem

The recovery mechanism does not work when the queues are created using RabbitAdmin.

**Comment by artembilan** [comment]
The problem that you do that manually with this plain code:
```
 rabbitAdmin.declareQueue(new Queue(queueName, false, false, true));
```

Meanwhile when it is a `@Bean`, the `RabbitAdmin` has this logic:
```
this.connectionFactory.addConnectionListener(connection -> {

        ...
	initialize();
	...
});
```

Scanning the application context for appropriate beans and call an idempotent `declare()` for them every time we get an new connection.

So, if you would like to have a re-create logic in your manual case, you need to think about your own `ConnectionListener` to be injected into the `ConnectionFactory`.

I don't think that there is some issue from the framework perspective and this is just a question, which should be addressed on StackOverflow.

**Comment by andcuevas** [comment]
If this is a framework limitation, there is no mention of it in the documentation.
In my use case I need to create the queues based on a variable list that comes from properties and RabbitAdmin is part of the framework.

**Comment by garyrussell** [comment]
The [documentation "Configuring the Broker"](https://docs.spring.io/spring-amqp/reference/html/_reference.html#broker-configuration) clearly states thats auto-configuration requires the elements (queues, exchanges, bindings) to be declared as beans.

You can create multiple elements with a single bean using a `Declarables` since version 2.1 (or `List<Declarable>` with earlier versions).

See [Declaring Collections of Exchanges, Queues, Bindings](https://docs.spring.io/spring-amqp/reference/html/_reference.html#collection-declaration).

Please make suggestions if you think the documentation needs improvement.

**Comment by andcuevas** [comment]
Thanks Gary for the clarification, English is not my first language and maybe is my limitation.
But it doesn't hurt to have an explicit comment in the section: https://docs.spring.io/spring-amqp//reference/html/_reference.html#auto-recovery

**Comment by jhassony** [comment]
I've encountered this issue as well. 
Since the framework disables the client's auto-recovery feature (and the documentation specifically says that Spring's auto-recovery replaces it completely), one would expect that every queue or binding that is declared using the framework would really be recoverable. Because this is not the case, it is also expected that enabling the underlying client's auto recovery will do the job, however, still, if the queue is not a bean in spring, it isn't recovered (and produces exceptions).
So is there any workaround for this?

**Comment by garyrussell** [comment]
Please open a new feature request issue; as long as the dynamically declared queues/bindings are declared through the `RabbitAdmin`, it could keep track of such declarations and re-declare them when the connection is re-established.

One work around is to keep track of the dynamic declarations yourself and add a connection listener to the connection factory (which is what `RabbitAdmin` does).

But the simplest would be to register them as beans so the admin will pick them up automatically.

**Comment by jhassony** [comment]
Thanks @garyrussell . I've created #1365
